### ISSUE TITLE
Deduplication of notifications

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn#12]
Should receivers and/or consumers be required to dedup identical notifications so the user doesn't see them twice?

eg. If I'm using a client that creates a post for me that mentions Alice (eg. via micropub/activitypub) and the client also sends notifications to Alice's inbox, but unbeknownst to the client my micro/activitypub endpoint _also_ sends inbox notifications to people mentioned upon new post creates, Alice will get the same notification twice. The bodies might be different if the client and my server decide to make slightly different json blobs, but there might be some fields with ids in that can be used for deduplicating.

This is way harder with arbitrary payload. Client might actually send a completely different notification to Alice than my server does.

**Comment by csarven** [comment]
I think if the payload is different, it is not subject to deduplication that the receiver/consumer should be after. Compare this to receiving two reposts or forwards of something. Is it different? Deduplication would be more like having multiple notifications with the same payload under different URLs. Even still:

I think this issue is out of scope because handling of the notifications is at the discretion of receivers/consumers. Maybe they want to keep them. There are probably equally important/useful scenarios so how do we cover them? It is difficult to give instructions on how receivers/consumers should go about doing that.

Did I understand you correctly?
