### ISSUE TITLE
Requires receivers store everything, even junk

### ISSUE THREAD

**Issue by aaronpk** [csarven/ldn#22]
I'm concerned about this:

> Upon receipt of a POST request to the Inbox, the receiver must create a new resource containing the RDF data from the body of the POST request and must return HTTP 201 Created with a Location header pointing to the created resource.

The problem is that this sentence requires that the receiver store invalid / spam / etc notifications. With my experience from receiving Pingbacks, the vast majority of requests my endpoint received were spam. In this case, you're basically asking an implementer to store junk notifications as well.

I'd suggest allowing the receiver to not store unverified notifications. Since you already have a section about what a verified notification means you can reference that. https://linkedresearch.org/ldn/#sender-verification

**Comment by akuckartz** [comment]
:+1:

**Comment by rhiaro** [comment]
Yeah, we should say they should do the create after passing it through whatever filter or validators they use according to their verification policy

**Comment by rhiaro** [comment]
Oops I closed that with the commit by accident. Is the new text okay?

**Comment by csarven** [comment]
@rhiaro 's commit is okay with me.

Perhaps applicable responses: 400, 403, 422 (WebDAV) that the receiver can make. Perhaps only 400 should be of interest? Is it okay to say 4xx in the spec or must specify individually?

202 could also work since the creation of the resource is at the discretion of the receiver. This is a catch all / asynchronous, also good signal back to the sender. There is the additional _ought_ to point status URL (which I don't particularly like to impose on the server - perhaps the receiver can omit that?).

**Comment by rhiaro** [comment]
I left the error code as 4xx because it's up to the receiver to say why they're rejecting it and we don't need to re-state http.

It's true adding it to a queue and sending back 202 prior to processing would also be okay. If the receiver is doing that, they should comply with http and send the status url, and presumably if they're implementing a queue anyway doing so is not a big ask.

**Comment by akuckartz** [comment]
There is no need to inform spammers with 4xx errors when they are not successful.

**Comment by csarven** [comment]
@akuckartz A receiver could reject a notification for any number of reasons, spam filtering being one. Recommending to return the appropriate error code for the situation doesn't hurt, but ultimately it's up to the receiver which one they respond with.

@aaronpk Are you satisfied with the current wording/coverage?

**Comment by aaronpk** [comment]
👍

**Comment by csarven** [comment]
Thanks.
