### ISSUE TITLE
Retry sending?

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn#26]
Do we need a SHOULD on retrying failed send attempts?

[PuSH](http://pubsubhubbub.github.io/PubSubHubbub/pubsubhubbub-core-0.4.html) says:

> Hubs SHOULD retry notifications repeatedly until successful (up to some reasonable maximum over a reasonable time period)

Which is suppose is saying its an implementation detail how you do it, but you should really think about doing it.

**Comment by csarven** [comment]
[HTTP 503](https://tools.ietf.org/html/rfc2616#section-10.5.4) mentions `Retry-After` header.

**Comment by rhiaro** [comment]
What if there's a `4xx`? The inbox could have gone, or there could just be a temporary network error.

**Comment by csarven** [comment]
I meant to say that `Retry-After` is the appropriate signal for 'retrying'. I should have pointed to https://tools.ietf.org/html/rfc2616#section-14.37 because that says that it could be used for `3xx`. I suppose PuSH's retry is about in the general sense of the word "until successful". That however doesn't particularly encourage the sender to pay attention to `Retry-After`.

I'm not sure if we have to worry about `4xx` in general other than what the RFC says. `401`, `407`, `408`, `411` are okay to retry. `400`, `403` not. I don't find a good reasons why a client would want to retry for `404`, `410`.

I agree that this should be `SHOULD` at most.

**Comment by rhiaro** [comment]
Because a 404 could be the server going down temporarily?

**Comment by csarven** [comment]
Sometimes a 404 is just a 404. The sender shouldn't question it. It is an implementation detail if for instance the sender is certain an Inbox URL exists and it gets something other than a 2xx - that'd be a bit like a stateful design. If a sender wants to retry, they can, but this is not something on the SHOULD level IMO.

**Comment by rhiaro** [comment]
We can leave this out, up to senders if they want to retry, or receivers if they want to send a 503 etc
