### ISSUE TITLE
Coment on HTML example in section 3.1 Discovery

### ISSUE THREAD

**Issue by nfreire** [csarven/ldn#44]
Hi,

In the example for "Discovering an Inbox with a GET request to retrieve HTML."
Currentlym this is used:

```
<a href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox">My inbox</a>
```

I was expecting that in HTML, the discovery of the inbox would be done from the header of the html with a link element. Something like:

```
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>A home-page</title>
    <link href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox" />
  </head>
  <body>...</body>
</html>
```

An element <a> would display the link for human users, which may happen to be desired in some cases, but I would not expect it to be frequent.

**Comment by csarven** [comment]
Given this discovery option:

> make a GET request on the target URL and, for RDF sources [RDF 1.1], the Inbox is the object of the predicate http://www.w3.org/ns/ldp#inbox.

It can actually be anywhere in the case of HTML if it is parsed as RDFa, i.e., `<link href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox" />` is just as possible. An HTML+RDFa parser (hence the body being an "RDF source") permits alternative possibilities, including but not limited to for example `property="http://www.w3.org/ns/ldp#inbox" href="/inbox/"` on any resource. An LDN discoverer can essentially treat text/html as HTML+RDFa. We treat it as RDFa so that any subject URI (especially including URIs with fragment identifiers in the document) can have their own inbox. On the other hand, if it is parsed only as HTML, the "subject" of the relation (for `@rel`) can only be the resolved URL. With RDFa, we cover both possibilities. So, in the case of `<link href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox" />` will have its subject (the "target") as the resolved URL in both HTML and HTML+RDFa parsing.

We can update the example to also mention the `<link href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox" />` possibility if that makes it more clear/necessary/desirable.

**Comment by nfreire** [comment]
Your explanation makes sense,
If I Interprete the example in relation to the RDF bullet point, it makes sense to me as it is.   

However for reader more familiar wirh HTTP than RDFa (like me) may find the example slightly confusing, because the text at the beginning of the section says:

> To discover the Inbox URL, senders and consumers:
> 
> make a HEAD or GET request on the target URL, to check for an HTTP Link header with a rel value of http://www.w3.org/ns/ldp#inbox

This is why I was expecting a link within the HEAD of the HTML.

So, concluding, I agree that updating the example to mention both cases would be an improvement..

**Comment by csarven** [comment]
I've updated the HTML+RDFa examples here: https://github.com/w3c/ldn/commit/6689b619cf0ff81568890c426fd1dde79fbe2d68 . May evolve those examples further but I think it addresses this issue.

**Comment by rhiaro** [comment]
Thanks for your input @nfreire!

> > make a HEAD or GET request on the target URL, to check for an HTTP Link header with a rel value of http://www.w3.org/ns/ldp#inbox
> 
> This is why I was expecting a link within the HEAD of the HTML.

The `HEAD` in this case refers to a HTTP `HEAD` request, rather than the `<head>` HTML element. Of course using `<link rel` in the `<head>` works too, but you'd retrieve this with a `GET` request, per the second bullet about checking the body of the document. We can rephrase to "make an HTTP HEAD or GET request on the target URL, to check for a Link header" so people don't trip up on this in future.

**Comment by nfreire** [comment]
Hi @rhiaro.
I was not hinting that only in HTML <HEAD> should be supported.
In my opinion, both cases are valid ways of publishing the inbox URL. 

The HTML <head> solution may be very important for web developers that do not have "permissions", or simply the knowledge, to control the HTTP headers in the responses.

**Comment by csarven** [comment]
@nfreire We entirely agree with you on those use cases, as they were used to derive at one of the discovery method. The spec gives the opportunity to senders and consumers to use either or both discovery methods. If you think that this issue is addressed, please feel free to close it.
