### ISSUE TITLE
Implementation of the OPTIONS request not mentioned in section 3.3

### ISSUE THREAD

**Issue by nfreire** [csarven/ldn#46]
Senders may send OPTIONS requests to receivers. In section 3.2:

> The sender may use an OPTIONS request to determine the RDF content types accepted by the server, and serialize the notification in the request body according to the value of the Accept-Post header [Accept-Post] returned.

The OPTIONS request is not mentioned in section 3.3 about the receiver. The Accept-post header is mentioned, but not the OPTIONS request in particular. Could mean that the Accept-post may only be supported in the POST responses of the receiver?

**Comment by nfreire** [comment]
Just noticed also that the OPTIONS request is not mentioned in the Receiver section of the implementations template:
https://github.com/w3c/ldn/tree/master/implementations

**Comment by csarven** [comment]
While Accept-Post is most likely to appear in OPTIONS, other methods may advertise it as well. For instance, the example under _Receiving notifications_ advertises it in the response to a HEAD request. We hint at it for the Senders, while Receivers can do their "off the shelf" HTTP behaviour. LDP for instance sets this as a SHOULD in OPTIONS for the Receivers.

The implementations template is still in progress. Updated the template to check if receivers are accepting OPTIONS requests. Thanks.

**Comment by nfreire** [comment]
My opinion is that section 3.3.1 should explicitly say something like:
Receivers SHOULD support OPTIONS HTTP requests and the response SHOULD contain the Accept-Post header.

**Comment by rhiaro** [comment]
So given that the official reference for `Accept-Post` is actually supposed to be the LDP spec rather than that IETF draft, and LDP specifies `OPTIONS` as a SHOULD, I've updated receivers to:

>  ... SHOULD advertise the content types they accept with an `Accept-Post` [Accept-Post] header in response to an `OPTIONS` request on the Inbox URL.

This isn't anything new/normativey different as the LDP Accept-Post spec already says that, but it makes it consistent with what is written in Sending.

I'm not keen to add a blanket SHOULD on `OPTIONS` for receivers, as it's only a SHOULD _if_ they want to accept anything other than JSON-LD. Otherwise there are no requirements on how they should respond to OPTIONS requests.

**Comment by nfreire** [comment]
Thanks for the feedback and for the improvement.
All is much more clear now.
